<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Yeseva+One&display=swap" rel="stylesheet">
</head>
<body>
<div>
    <div>
        <form method="post">
            <div>
                <input type="text" placeholder="first_name" name="first_name">
            </div>
            <div>
                <input type="text" placeholder="last_name" name="last_name">
            </div>
            <div>
                <input type="text" placeholder="numberOfPassport" name="numberOfPassport">
            </div>
            <div>
                <input type="text" placeholder="age" name="age">
            </div>
            <div>
                <input type="text" placeholder="state" name="state">
            </div>
            <div>
                <input type="text" placeholder="date" name="date">
            </div>
            <input type="submit" value="Отправить">
        </form>
    </div>
</div>
</body>
</html>